// <auto-generated />
using System;
using GeometriaFactory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeometriaFactory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GeometriaFactoryDbContext))]
    partial class GeometriaFactoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("GeometriaFactory.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_Account_NormalizedEmail");

                    b.HasIndex("Role")
                        .IsUnique()
                        .HasDatabaseName("UX_Account_SingleAdministrator")
                        .HasFilter("\"Role\" = 'Administrator'");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("GeometriaFactory.Domain.Entities.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("DeclaredArea")
                        .HasColumnType("REAL");

                    b.Property<double?>("DeclaredLength")
                        .HasColumnType("REAL");

                    b.Property<double?>("DeclaredRadius")
                        .HasColumnType("REAL");

                    b.Property<double?>("DeclaredWidth")
                        .HasColumnType("REAL");

                    b.Property<Guid>("PieceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PieceId");

                    b.ToTable("Componente", (string)null);
                });

            modelBuilder.Entity("GeometriaFactory.Domain.Entities.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("DeclaredValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("DerivedValue")
                        .HasColumnType("REAL");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PiecePosition")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkId");

                    b.ToTable("Observacion", (string)null);
                });

            modelBuilder.Entity("GeometriaFactory.Domain.Entities.Piece", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("DeclaredArea")
                        .HasColumnType("REAL");

                    b.Property<double?>("DeclaredLength")
                        .HasColumnType("REAL");

                    b.Property<double?>("DeclaredRadius")
                        .HasColumnType("REAL");

                    b.Property<double?>("DeclaredVolume")
                        .HasColumnType("REAL");

                    b.Property<double?>("DeclaredWidth")
                        .HasColumnType("REAL");

                    b.Property<double?>("DerivedArea")
                        .HasColumnType("REAL");

                    b.Property<double?>("DerivedVolume")
                        .HasColumnType("REAL");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkId", "Position")
                        .IsUnique();

                    b.ToTable("Pieza", (string)null);
                });

            modelBuilder.Entity("GeometriaFactory.Domain.Entities.Work", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdministratorComment")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeclaredDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RootFigureCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Status")
                        .HasDatabaseName("IX_Work_Owner_Status");

                    b.ToTable("Work", (string)null);
                });

            modelBuilder.Entity("GeometriaFactory.Domain.Entities.Component", b =>
                {
                    b.HasOne("GeometriaFactory.Domain.Entities.Piece", null)
                        .WithMany("Components")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeometriaFactory.Domain.Entities.Observation", b =>
                {
                    b.HasOne("GeometriaFactory.Domain.Entities.Work", null)
                        .WithMany("Observations")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeometriaFactory.Domain.Entities.Piece", b =>
                {
                    b.HasOne("GeometriaFactory.Domain.Entities.Work", null)
                        .WithMany("Pieces")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeometriaFactory.Domain.Entities.Work", b =>
                {
                    b.HasOne("GeometriaFactory.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeometriaFactory.Domain.Entities.Piece", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("GeometriaFactory.Domain.Entities.Work", b =>
                {
                    b.Navigation("Observations");

                    b.Navigation("Pieces");
                });
#pragma warning restore 612, 618
        }
    }
}
